### ISSUE TITLE
Slice bounds out of range while parsing a prop list

### ISSUE THREAD

**Issue by medusalix** [jfreymuth/pulse#17]
It seems like there's an edge case where parsing an element of a prop list returns a length of zero causing an out-of-bounds:

https://github.com/jfreymuth/pulse/blob/1534c4af9659488c8e0e55f7ab38eb6b49e13261/proto/reader.go#L174

I can't reproduce this reliably, so I hope this stack trace helps:

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 7 [running]:
github.com/jfreymuth/pulse/proto.(*ProtocolReader).propList(0xc000182000, 0xc0001b4690)
	/home/krem/go/pkg/mod/github.com/jfreymuth/pulse@v0.0.0-20200506145638-1534c4af9659/proto/reader.go:174 +0x2a3
github.com/jfreymuth/pulse/proto.(*ProtocolReader).value(0xc000182000, 0x7ffbe0, 0xc000258480, 0x20)
	/home/krem/go/pkg/mod/github.com/jfreymuth/pulse@v0.0.0-20200506145638-1534c4af9659/proto/reader.go:262 +0x71c
github.com/jfreymuth/pulse/proto.(*Client).parseInfoList(0xc000182000, 0x7ffb80, 0xc00022a340, 0x958)
	/home/krem/go/pkg/mod/github.com/jfreymuth/pulse@v0.0.0-20200506145638-1534c4af9659/proto/client.go:236 +0x858
github.com/jfreymuth/pulse/proto.(*Client).readLoop(0xc000182000)
	/home/krem/go/pkg/mod/github.com/jfreymuth/pulse@v0.0.0-20200506145638-1534c4af9659/proto/client.go:136 +0x36a
created by github.com/jfreymuth/pulse/proto.(*Client).Open
	/home/krem/go/pkg/mod/github.com/jfreymuth/pulse@v0.0.0-20200506145638-1534c4af9659/proto/client.go:48 +0x12c
```

**Comment by jfreymuth** [comment]
Interesting... I initially assumed proplist entries are always null-terminated strings, but apparently that's not true.

Fix is on the way, but I want to do it right.

**Comment by medusalix** [comment]
Thank you :smiley:.
