### ISSUE TITLE
Send on closed channel panic on RecordStream.Close() after error

### ISSUE THREAD

**Issue by at-wat** [jfreymuth/pulse#21]
Calling `RecordStream.Close()` after error causes `panic: send on closed channel`.
I think `proto.Client.Send()` and `proto.Client.Request()` are better to return error if the client is already closed or errored.
 
```
panic: send on closed channel

goroutine 1531535 [running]:
github.com/jfreymuth/pulse/proto.(*Client).Request(0xc000aea180, 0xf46100, 0xc0006b09b0, 0x0, 0x0, 0xc000359c01, 0xc000530001)
	/go/pkg/mod/github.com/jfreymuth/pulse@v0.0.0-20200817093420-a82ccdb5e8aa/proto/client.go:83 +0x385
github.com/jfreymuth/pulse.(*RecordStream).Close(0xc0003d2140)
	/go/pkg/mod/github.com/jfreymuth/pulse@v0.0.0-20200817093420-a82ccdb5e8aa/record.go:97 +0x88
github.com/pion/mediadevices/pkg/driver/microphone.(*microphone).AudioRecord.func2(0x411a86, 0xc0007eab10, 0x30, 0x30)
	/go/pkg/mod/github.com/pion/mediadevices@v0.0.0-20200907043325-0cd870fd4bae/pkg/driver/microphone/microphone_linux.go:103 +0x1b0
github.com/pion/mediadevices/pkg/io/audio.ReaderFunc.Read(0xc000aec280, 0x0, 0x203000, 0xc0007ff000, 0x0)
	/go/pkg/mod/github.com/pion/mediadevices@v0.0.0-20200907043325-0cd870fd4bae/pkg/io/audio/audio.go:14 +0x27
github.com/seqsense/sq-video-gw/video-sender/audiowatchdog.New.func1.2(0x203000, 0x203000, 0x203000, 0xbd23a0)
	/go/src/seqsense/sq-video-gw/video-sender/audiowatchdog/audiowatchdog.go:34 +0x4e
github.com/pion/mediadevices/pkg/io/audio.ReaderFunc.Read(0xc000573740, 0xf1, 0x2, 0x0, 0xc0007e4a40)
	/go/pkg/mod/github.com/pion/mediadevices@v0.0.0-20200907043325-0cd870fd4bae/pkg/io/audio/audio.go:14 +0x27
github.com/pion/mediadevices/pkg/io/audio.NewBuffer.func1.1(0x400, 0xc0007e4a20, 0xc0007e4a40, 0x1)
	/go/pkg/mod/github.com/pion/mediadevices@v0.0.0-20200907043325-0cd870fd4bae/pkg/io/audio/buffer.go:22 +0x9d
github.com/pion/mediadevices/pkg/io/audio.ReaderFunc.Read(0xc000573800, 0xc000359e88, 0x40a935, 0xc000390180, 0xc000359f08)
	/go/pkg/mod/github.com/pion/mediadevices@v0.0.0-20200907043325-0cd870fd4bae/pkg/io/audio/audio.go:14 +0x27
github.com/pion/mediadevices/pkg/io/audio.NewChannelMixer.func1.1(0x38cbf4d9d587d, 0xc00041a160, 0xc000a026c0, 0xc0006b0988)
	/go/pkg/mod/github.com/pion/mediadevices@v0.0.0-20200907043325-0cd870fd4bae/pkg/io/audio/mixer.go:12 +0x5c
github.com/pion/mediadevices/pkg/io/audio.ReaderFunc.Read(0xc000573830, 0xc000359f68, 0xb04364, 0xc0008149b0, 0xc000af3400)
	/go/pkg/mod/github.com/pion/mediadevices@v0.0.0-20200907043325-0cd870fd4bae/pkg/io/audio/audio.go:14 +0x27
github.com/pion/mediadevices/pkg/codec/opus.(*encoder).Read(0xc0005737d0, 0xc000af3400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/pion/mediadevices@v0.0.0-20200907043325-0cd870fd4bae/pkg/codec/opus/opus.go:76 +0x38
github.com/pion/mediadevices.(*track).start(0xc0003fa230)
	/go/pkg/mod/github.com/pion/mediadevices@v0.0.0-20200907043325-0cd870fd4bae/track.go:156 +0x7d
created by github.com/pion/mediadevices.newTrack
	/go/pkg/mod/github.com/pion/mediadevices@v0.0.0-20200907043325-0cd870fd4bae/track.go:112 +0x4cc
```

**Comment by jfreymuth** [comment]
`proto.Client.Request()` already checks for errors, but there was a race condition.
Should be fixed by 56c643689bfc6a28854e9bdd7ed837ea92de52e8
